### ISSUE TITLE
480x800 config ?

### ISSUE THREAD

**Issue by stuaxo** [adafruit/Adafruit-DPI-Kippah#1]
Hi,
   Is the a 480x800 variation ?

Cheers
S

**Comment by ladyada** [comment]
you can set any config, set hdmi_timings= to whateve ryou like

**Comment by stuaxo** [comment]
Cheers, its a long time since I was getting paid to work on a raspberry pi + kippah display board project.

I wasn't sure on the specific timings to make the display work in portrait.

We solved it in the end (though not sure if correctly), I'd have to dig a pi out of a box to see what we did.
