### ISSUE TITLE
Not working for tinkerboard

### ISSUE THREAD

**Issue by shreshthtuli** [adafruit/Adafruit-DPI-Kippah#2]
I tried to make this work with ASUS tinkerboard but it isnt working. Is there any way by which the same adapter can be used to display using GPIO pins on ASUS tinkerboard?

**Comment by ladyada** [comment]
that is incredibly unsurprising as it relies on a hardware peripheral on the bcm chip. it probably will not ever work! please contact asus for advice on connecting a TTL TFT display, they'll know their chip best
